<a href="https://colab.research.google.com/github/iamanolive/iiit-allahabad-courses/blob/main/machine-learning%5C2-data-analysis%5C4-basics-of-numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [37]:
import numpy as np

## one-dimensional arrays

In [38]:
a = np.array([1, 2, 3, 4])
type(a)

numpy.ndarray

In [39]:
a.shape

(4,)

In [40]:
a[1]

2

In [41]:
a[2] = 5
a

array([1, 2, 5, 4])

## multi-dimensional arrays

In [42]:
b = np.array([
    [1, 2, 3],
    [5, 6, 7]
])

In [43]:
b.shape

(2, 3)

In [44]:
np.array([4, 5, 676, 5], dtype = float)

array([  4.,   5., 676.,   5.])

In [45]:
type(np.array([4, 5, 676, 5], dtype = float))

numpy.ndarray

In [46]:
a[:3]

array([1, 2, 5])

## multiplying individual elements

In [47]:
a

array([1, 2, 5, 4])

In [48]:
3 * a

array([ 3,  6, 15, 12])

In [49]:
b

array([[1, 2, 3],
       [5, 6, 7]])

In [50]:
3 * b

array([[ 3,  6,  9],
       [15, 18, 21]])

## array functions

In [51]:
3 in b

True

In [52]:
3 not in b

False

In [53]:
a.fill(1)

In [54]:
a

array([1, 1, 1, 1])

## identity matrix

In [55]:
eye = np.eye(4)
print(eye)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [56]:
one = np.ones(4)
print(one)

[1. 1. 1. 1.]


In [57]:
one = np.ones((2, 3))
print(one)

[[1. 1. 1.]
 [1. 1. 1.]]


In [58]:
zero = np.zeros((3, 5))
print(zero)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [59]:
d = np.full((3, 3), 7)

In [60]:
d

array([[7, 7, 7],
       [7, 7, 7],
       [7, 7, 7]])

## mathematical operations

In [61]:
d.sum()

63

In [62]:
np.sum(d)

63

In [63]:
d.prod()

40353607

In [64]:
d.mean()

7.0

In [65]:
d.std()

0.0

## the arange function

In [67]:
n = np.arange(5)

In [68]:
n

array([0, 1, 2, 3, 4])

In [71]:
m = np.arange(5, 11)

In [72]:
m

array([ 5,  6,  7,  8,  9, 10])

In [73]:
even = np.arange(0, 10, 2)

In [74]:
even

array([0, 2, 4, 6, 8])

## the random function

In [75]:
ran = np.random.rand(5)

In [77]:
ran # 5 random values between 0 and 1

array([0.77694251, 0.63001432, 0.58311791, 0.8070171 , 0.96072479])

In [78]:
ran1 = np.random.rand(2, 3)

In [80]:
ran1 # 2 rows, 3 columns

array([[0.279616  , 0.24556533, 0.92678715],
       [0.00905216, 0.51970255, 0.04104847]])

In [81]:
ran2 = np.random.randint(2, 45)

In [85]:
np.random.randint(2, 45)

19

In [86]:
np.random.randint(2, 45)

8

In [87]:
np.random.randint(2, 45)

5

## dot product of arrays

In [88]:
arr1 = np.array([3, 4])
arr2 = np.array([2, 3])

In [89]:
print(10 * np.dot(arr1, arr2))

180


In [90]:
print(np.dot(arr1, arr2))

18
